### PR TITLE
Make GEOPHIRES consumable as a Python module; add deprecation notice

### PR DESCRIPTION
**Pull request by softwareengineerprogrammer**
Minimal set of changes necessary to make GEOPHIRES consumable as a Python module. See documentation added in README for example/explanation. Does not change any simulation parameters or functionality except making input and output files named parameters that can be optionally overridden.

### CODE REVIEW

**Comment by softwareengineerprogrammer** [comment]
Addresses https://github.com/NREL/GEOPHIRES-v2/issues/3

**Comment by softwareengineerprogrammer** [comment]
@kfbeckers May I suggest we merge this now that GEOPHIRES-X has been announced/released?

**Comment by kfbeckers** [comment]
Hi Jonathan,

Sounds good! Yes, let me know please what I need to do on my end.

Thanks,
Koenraad

**Comment by softwareengineerprogrammer** [comment]
@kfbeckers You should see a button that says "Merge pull request" on this page, that's the one you want to click.

**Comment by kfbeckers** [comment]
Looks great. However, we should change the link in the readme deprecation message to https://github.com/nrel/python-geophires-x/

**Comment by softwareengineerprogrammer** [comment]
Closed in favor of https://github.com/NREL/GEOPHIRES-v2/commit/08485b98ae02aeb7a5acd972f906b2ea81ae2647

**Pull request closed without merging**
